#!/bin/bash
# GEE认证辅助脚本
echo "=========================================="
echo "Google Earth Engine 认证"
echo "=========================================="
echo ""
echo "如果你已有GEE账号，请运行以下命令完成认证:"
echo ""
echo "  earthengine authenticate"
echo ""
echo "步骤:"
echo "  1. 运行上述命令"
echo "  2. 终端会显示一个URL"
echo "  3. 在浏览器中打开该URL"
echo "  4. 用Google账号登录并授权"
echo "  5. 复制授权码粘贴回终端"
echo ""
echo "认证完成后，运行以下脚本下载数据:"
echo "  python /workspace/xuannv/scripts/preprocessing/download/download_gee_haidian.py"
echo "=========================================="
