"""修复图10的中文显示问题，全部改为英文"""
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['Arial', 'DejaVu Sans', 'Liberation Sans'],
    'axes.unicode_minus': False,
    'figure.facecolor': 'white',
    'axes.facecolor': 'white',
    'savefig.facecolor': 'white',
    'savefig.dpi': 300,
})

C_PRIMARY = '#1a5276'
C_SECONDARY = '#5dade2'
C_NEUTRAL = '#7f8c8d'
C_GRID = '#d5dbdb'
C_TEXT = '#2c3e50'

OUTPUT_DIR = "/workspace/xuannv/references/charts"

fig, ax = plt.subplots(figsize=(11, 5))
ax.set_xlim(0, 11)
ax.set_ylim(0, 5)
ax.axis('off')

# Left panel: Input
rect_left = plt.Rectangle((0.3, 1.0), 4.5, 3.5, facecolor='#f8f9f9', edgecolor=C_GRID, linewidth=1.5)
ax.add_patch(rect_left)
ax.text(2.55, 4.2, 'Natural Language Input', ha='center', va='center', fontsize=11, fontweight='bold', color=C_PRIMARY)

input_text = '"Summarize construction land changes\nin Harbin from Apr to Oct 2025,\nand generate a comparison report."'
ax.text(2.55, 3.0, input_text, ha='center', va='center', fontsize=9, color=C_TEXT,
        bbox=dict(boxstyle='round,pad=0.5', facecolor='white', edgecolor=C_SECONDARY, linewidth=1.5))
ax.text(2.55, 1.6, 'User prompt in plain Chinese', ha='center', va='center', fontsize=8, color=C_NEUTRAL, style='italic')

# Right panel: Output
rect_right = plt.Rectangle((6.2, 1.0), 4.5, 3.5, facecolor='#f8f9f9', edgecolor=C_GRID, linewidth=1.5)
ax.add_patch(rect_right)
ax.text(8.45, 4.2, 'AI-Generated Report', ha='center', va='center', fontsize=11, fontweight='bold', color=C_PRIMARY)

output_lines = [
    '## Harbin Construction Land Change Analysis',
    '',
    '| District | Area (km2) | Rate |',
    '|----------|------------|------|',
    '| Songbei  | 12.3       | +8.2%|',
    '| Daoli    | 5.7        | +3.1%|',
    '',
    '> Main change type: Farmland -> Construction',
    '',
    '*Generated by DeepSeek AI*'
]
for j, line in enumerate(output_lines):
    ax.text(8.45, 3.4 - j*0.22, line, ha='center', va='top', fontsize=7.5, color=C_TEXT,
            family='monospace')

# Center arrow
ax.annotate('', xy=(6.0, 2.75), xytext=(4.9, 2.75),
            arrowprops=dict(arrowstyle='->', color=C_PRIMARY, lw=2.5))
ax.text(5.45, 3.0, 'DeepSeek\nV4', ha='center', va='bottom', fontsize=8, fontweight='bold', color=C_PRIMARY)

# Bottom pipeline
pipeline_steps = ['flash\nparse', 'task\nexecute', 'pro\npolish']
pipeline_x = [1.5, 5.5, 9.5]
for x, step in zip(pipeline_x, pipeline_steps):
    circle = plt.Circle((x, 0.5), 0.35, facecolor=C_SECONDARY, edgecolor=C_TEXT, linewidth=1.0, alpha=0.85)
    ax.add_patch(circle)
    ax.text(x, 0.5, step, ha='center', va='center', fontsize=8, fontweight='bold', color='white')

for i in range(len(pipeline_x)-1):
    ax.annotate('', xy=(pipeline_x[i+1]-0.4, 0.5), xytext=(pipeline_x[i]+0.4, 0.5),
                arrowprops=dict(arrowstyle='->', color=C_NEUTRAL, lw=1.2))

ax.text(5.5, -0.15, 'Pipeline: flash parses prompt -> executor fetches data -> pro polishes report',
        ha='center', fontsize=8, color=C_NEUTRAL, style='italic')

ax.set_title('AI Agent: Natural Language -> Remote Sensing Report', fontsize=14, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/10_agent_report.png', bbox_inches='tight')
plt.close()
print("[OK] Chart 10 fixed (English only)")
